from django.core.management.base import BaseCommand, CommandError
from lit_search.models import Article


class Command(BaseCommand):
  args = '<Article_filname>'
  help = "Imports a gzipped file generated by Max's literature search pipeline"

  def handle(self, *args, **options):
    try:
      article_filename = args[0]
      self.stdout.write(article_filename)
    except:
      raise BaseException("Incorrect number of arguments for import")

    Article.import_articles(article_filename)
